### ISSUE TITLE
Initial Stable Release?

### ISSUE THREAD

**Issue by navulirs** [jfrog/artifactory-user-plugins#124]
Any thoughts on when the stable release will be made available? We are looking into having conda package manager work with Artifactory.

Thanks.

**Comment by markgalpin** [comment]
What do you mean by stable release?  Plugins in artifactory-user-plugins are usually committed after being used by a customer.  The conda plugin, for example, works as advertised with current versions of artifactory and is being used by several customers in production.  Support for user plugins is more limited than that provided for product features (that is JFrog takes responsibility to test them on new versions, but doesn't typically respond to feature requests, performance issues etc.) They are, in the end user extensions to the product.  We may eventually build a similar feature into the product (a number of user plugins have been deprecated because of the existence of a related product feature) but don't guarantee it.
