### ISSUE TITLE
Conda plugin should allow caching packages from remote conda channels

### ISSUE THREAD

**Issue by vinjana** [jfrog/artifactory-user-plugins#221]
Conda packages are not kept available for ever in some channels (e.g. bioconda). The artifactory should keep packages (+ metadata) and all their dependencies from remote repositories, even if the package is removed upstream.

Application area: We develop data processing workflows that depend on many conda packages. Caching would make it easy to provide support for specific workflow versions over a longer time period to internal users and would enormously improve scientific reproducibility.

**Comment by elioengcomp** [comment]
Hi @vinjana ,

If you don't enable unused artifacts cleanup (disabled by default) Artifactory will keep copies of the remote packages in the local cache, even if it is removed from the source. The problem here is the metadata/index. When a package is removed from the upstream and the index is updated, the package entry is removed from the index. When there is a new version of the index file in the upstream, it will be downloaded by Artifactory and updated in the local cache. This makes it very difficult to protect remote caches from deletions.

One alternative to protect your environment from deletions in the upstream is to promote (copy) the used packages from the remote to a local repository, and use this local repo to resolve dependencies. Doing that you completely isolate your environment from the external repo, and use it  more like a store for dependencies.

**Comment by vinjana** [comment]
Thanks @elioengcomp for the clarification. I see that some kind of merging of local and remote indices/metadata would be necessary. So you estimate the effort to implement a merging of metadata from upstream with local higher than the effort to set up an independent system (e.g. using repeated re-indexing) from the scratch?

**Comment by elioengcomp** [comment]
@vinjana in Artifactory, the merging of metadata that you mentioned is handled by virtual repositories. Unfortunately, the user plugin that we have to support conda does not support virtual repositories. We don't plan to add this support to the user plugin because we believe this should be a product feature in Artifactory. We have plans to add conda as a supported package type in Artifactory, as announced during SwampUp this year. As soon as we release that the user plugin may be deprecated.

**Comment by DarthFennec** [comment]
>We don't plan to add this support to the user plugin because we believe this should be a product feature in Artifactory.

While this is true, I would like to add also that it is currently impossible to write a user plugin that deals with metadata in virtual repositories. The API doesn't allow it.

**Comment by DarthFennec** [comment]
Conda is supported natively by Artifactory as of 6.3, and this plugin is deprecated, so I'm closing this for now.
