### ISSUE TITLE
artifactCleanup: Introduction of enhanced support for arbitrary time intervals?

### ISSUE THREAD

**Issue by AlexanderDenk-EE** [jfrog/artifactory-user-plugins#227]
Hello,

we are running a very large Artifactory instance that is storing a lot of short-living artifacts. A lot of the artifacts are of interest for about one up to two weeks. Sadly the *artifactCleanup*-plugin does only support a minimum lifetime of one month to delete the unused artifacts. For our use case this is a pretty long interval where we are storing unused artifacts. This leads to a much larger storage consumption than actually needed which therefore slows down the backup processes and so on...
Basically it's pretty easy to tune the plugin to support a configurable timespan.

For example I've split up the `month` parameter into two separate parameters:
* `timeUnit (enum: year, month, day, hour, minute)` 
* `timeInterval (int)`

This enables the user of the plugin to define a arbitrary timespan when artifacts can be cleaned up.

As far as I can see the change could be interesting for other Artifactory users, so I would like to contribute the code to this project:

* *I could create a PR for the current plugin:* This would be my favored way to go, but as the parameters are renamed, the PR will break the current usages of the plugin. Keeping the support for the `month` parameter would be possible, but confusing for new users.
* *I could* create a PR with a new plugin:* This would ensure the current plugin stays compatible, but it would also introduce a huge amount of duplicated code.

 Are there any opinions which way to go and are there any best practices for breaking compatibility?

Thanks for every feedback,
Alex

**Comment by DarthFennec** [comment]
I think the best approach would be to create a PR for the existing plugin, and keep support for the `months` parameter. I don't think it would be all that confusing for new users, as long as the old parameter was marked in the README as deprecated in favor of the new parameters.

Breaking compatibility isn't an invalid option, and has happened a number of times with these plugins in the past. As far as I know, people generally only update their plugins when they have a good reason (incompatibility with Artifactory upgrades, new plugin features they'd like to use, etc), so as long as the new behavior is properly documented, the "surprise factor" of the plugin not working due to an out-of-date config is usually minimal, from what I can tell.

**Comment by elioengcomp** [comment]
Hi @AlexanderDenk-EE 

Thanks for the valuable feedback and interest in contributing.

I would recommend the following:

- Introduce the new `timeUnit` parameter as an optional parameter. Set the default value to `month`;
- Introduce the new `timeInterval` parameter;
- Keep the current `month` parameter as an alias to the new `timeInterval` parameter just to keep this new implementation backwards compatible with current usages of this plugin;

**Comment by AlexanderDenk-EE** [comment]
Thank you both for your responses.

I just checked out if it would be possible to build in a fallback support for the deprecated parameter. This would be easy for the url-parameter, but it gets tricky if it comes to the *artifactCleanup.properties policies*. Here we have a 0-indexed array where a kind of duck-typing would be needed to determine if the old month parameter is used or the new ones. This can be done, but it increases complexity and decreases the maintainability of the plugin. Also much more test cases would be needed to cover both variants and ensure both are working correctly.

Therefore i would suggest the following way to go:
* Update the documentation with a clear statement that the *month*-parameter was removed.
* Build in a clear *log.error* message, if the *months* parameter is detected in a url, or if the policies do not contain a valid timeUnit.
 
This would lead to an transparent behavior for updating the plugin and would keep the code clear, testable and maintainable.

Any concerns?

**Comment by elioengcomp** [comment]
@AlexanderDenk-EE 

To make the `timeUnit` parameter optional in artifactCleanup.properties file, you can introduce it as the last parameter. During runtime, you can assign the default value to it if the policy configuration array has less than 7 elements.

About the tests, we will need to create new tests anyway. I believe the creation of the new `timeUnit` parameter is the change that will make the tests more complex, not the fallback mechanism. By the way, we can use the existing test case as a regression test to validate the fallback mechanism, since it is based on the current implementation.

We can help you with the test cases writing. At this moment, we don't require public contributions to write test cases at all. We can do it for you if you don't have the time. Although, If you do it, it will be really helpful =)

I believe it is very important to keep the plugin backwards compatible so we don't create unplanned and undesired work for users using this plugin when they decide to update to the latest version. Even if the changes are well documented, customers can have their retention policies spread across multiple Artifactory instances or Jenkins jobs and the impact of fixing them all can be huge.

**Comment by DarthFennec** [comment]
I've never really liked the `artifactCleanup.properties` file. Since it's an array instead of a map, each time we add a parameter to it, it becomes harder to maintain properly. For example, if the check is "less than seven elements", that's fine for now, but what if we add new properties later? And what if they're also optional? As much as I agree that suddenly breaking backwards compatibility would cause problems for users, I think in the long run it would cause more problems to preserve compatibility in this case.

How about this. We keep support for the `artifactCleanup.properties` file, as-is, and never change it again. We create a new `artifactCleanup.json` format that takes precedence, and we add all new configuration options to that format. This way, if someone needs the newest version for a bugfix or something, it will continue to work with their config, but if they need new features that introduce more config options, they need to switch to the new format. No surprises.

**Comment by AlexanderDenk-EE** [comment]
Actually I would prefer this solution. It would keep the plugin much more cleaner for future development.

**Comment by elioengcomp** [comment]
@AlexanderDenk-EE it looks good!

**Comment by AlexanderDenk-EE** [comment]
Thank you for the feedback, I'll create a PR on Monday. Have a nice weekend.

**Comment by elioengcomp** [comment]
Cool!

Have a nice weekend too.
