### ISSUE TITLE
How to delete a subdirectory in a repository

### ISSUE THREAD

**Issue by tiffanyzhou** [jfrog/artifactory-user-plugins#243]
I downloaded the artifactCleanup.groovy file and successfully configured the parameters, but I want to delete only one directory when i delete it. For example:

generic-local (my repository)
--dev
--release

when I run "http://localhost:8080/artifactory/api/plugins/execute/cleanup?params=timeUnit=month;timeInterval=1;**repos=generic-local**;paceTimeMS=2000" It works.

when I run "http://localhost:8080/artifactory/api/plugins/execute/cleanup?params=timeUnit=month;timeInterval=1;**repos=generic-local/dev**;paceTimeMS=2000" It doesn't works.

How can I delete a subdirectory?

**Comment by DarthFennec** [comment]
Right now it can only clean entire repositories, not just a single directory inside of a repository. Usually people have separate repositories for dev and release.

If you just want to make sure `release` is never cleaned, you can create a `cleanup.skip: true` property on that folder to disable cleanup for it.

**Comment by tiffanyzhou** [comment]
How can I create a cleanup. skip? Is it a file or a directory or just a parameter in command?

**Comment by tiffanyzhou** [comment]
I already know how to set cleanup. skip in Artifactory UI, thanks
but setup a artifactCleanup.json,cron it seems doesn't work , whether other properties need to be configuration necessarily?
{
    "policies": [
        {
            "cron": "0 17 4 * * ?",
            "repos": [
                "ECF"
            ],
            "timeUnit": "minute",
            "timeInterval": 3,
            "dryRun": false,
            "paceTimeMS": 500,
            "disablePropertiesSupport": false
        }
    ]
}

**Comment by DarthFennec** [comment]
What you have looks right to me. You shouldn't need anything other than the `cleanup.skip` property set to `true` on your folder, and `"disablePropertiesSupport": false` in your configuration, both of which you have. Perhaps the plugin needs reloading? If you change the configuration file without reloading the plugin or restarting Artifactory, the plugin might be still using the old configuration. If you use the REST API to reload the plugin, you might need to make a minor change to the groovy file first, otherwise Artifactory might not think it needs to be reloaded.

**Comment by tiffanyzhou** [comment]
I reload the plugin and it will run, thanks a lot.

**Comment by tiffanyzhou** [comment]
I have a new question, how to clean up repo, if there is only one version of an artifact, no matter how long I want to keep it, if there are many versions of an artifact, I just want to keep the latest one, is that supported? Or is there any way I can do it on my own.

**Comment by DarthFennec** [comment]
Sincere apologies for the very long wait, this must have gotten lost in the shuffle somewhere. So it sounds like you want to clean all but the most recent version of each package, instead of those beyond a certain age? This isn't supported by `artifactCleanup`, but there's a pull request (#187) for a new plugin that appears to be specifically for this. If you're using a Docker repository, I think [`cleanDockerImages`](https://github.com/jfrog/artifactory-user-plugins/tree/master/cleanup/cleanDockerImages) can do it this way too, but that doesn't seem to be your use case.
