### ISSUE TITLE
Cannot Login to Docker Repository

### ISSUE THREAD

**Issue by Shereind** [jfrog/artifactory-user-plugins#258]
I downloaded artifactory 6.6.0 on remote desktop with ip (x.x.x.x) and connect to port 8081.

I can connect to artifactory from my computer http://x.x.x.x:8081/artifactory. I have docker client on my computer but I don't have docker on remote desktop.

I have virtual docker repository named "docker".

I want to login by docker client to my docker repository on artifactory -> "docker login " and then pull images in this repository.
I tried "docker login Artifactory-docker.jfrog.io" and "docker login x.x.x.x-docker.jfrog.io"  but it didnt work

How can I log in and pull images from artifactory? 
Notice I don't have SSL so I'm using HTTP.

**Comment by DarthFennec** [comment]
I'd suggest you read [the documentation](https://www.jfrog.com/confluence/display/RTF/Getting+Started+with+Artifactory+as+a+Docker+Registry), which describes how to set up your Artifactory Docker registry so that you can access it. It used to be that you needed to set up a reverse proxy (such as Nginx), but more recently there's a more straightforward method that uses Artifactory's embedded Tomcat instance. However you do it, you'll need to log in using your local IP address and port, not using `jfrog.io`.

For future reference, this Github is for user plugins, not general Artifactory issues. For questions like this, it's preferred that you file a support ticket instead.
