### ISSUE TITLE
webhook: docker.tagCreated is triggered if the manifest.json is modified

### ISSUE THREAD

**Issue by aflag** [jfrog/artifactory-user-plugins#272]
We have been getting a lot of docker.tagCreated events when the manifest.json file is merely modified and no creation is actually taking place.  We noticed this change only when we upgraded from artifactory 6.7.0 to 6.9.1, but it could be present in earlier versions.

**Comment by elioengcomp** [comment]
HI @aflag 

pt-BR: Obrigado por entrar em contato! / en-US: Thank you for your message!

The plugin uses the manifest.json file to identify changes in docker tags. In Artifactory, an artifact overwrite is executed as a delete followed by a write. That will trigger both tagDeleted and tagCreated webhook plugin events. So the behavior you are seeing is by design.

**Comment by aflag** [comment]
Oi Elio,

Getting a tagCreated event from a remote repo when the previous tag was actually the exactly same thing, with the same digest and layers, is a bit misleading, though. That seems to happen to us after the  Metadata Retrieval Cache Period expires (I assume it will automatically download a new version of the manifest.json file, even if nothing has changed). It'd be nice if we could have a way to know what caused the tagCreated event to be triggered, so we could ignore it in those situations.

**Comment by elioengcomp** [comment]
> I assume it will automatically download a new version of the manifest.json file, even if nothing has changed
I need to run some tests to confirm this, but I believe it should not be the case.

**Comment by jfrog-aparicio** [comment]
Will not fix as this plugin has been deprecated in favor of the built-in Artifactory webhook feature.
