### ISSUE TITLE
Force Reloading a User Plugin

### ISSUE THREAD

**Issue by sarathkrishna2018** [jfrog/artifactory-user-plugins#288]
The following is my sample code:

`storage{
//(xyz operations)
beforeCreate{
//(abc operations using data from xyz operations)
}
}`

In this case, where I have written code in storage block outside beforeCreate block, I have noticed that, this specific code is executed only when the plugin is loaded/reloaded. I need to fetch some data only when it has changed using the code here. But it executes only when its reloaded. Is there any way to force-reload this plugin?

**Comment by DarthFennec** [comment]
There is a [plugin reload API](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-ReloadPlugins) you can call. However, this only works if the plugin file itself has been modified, otherwise Artifactory will decide that it doesn't need to be reloaded.

If you're not planning on changing the plugin code itself, another option is to put your `xyz operations` in a function that modifies some global variables, and then run that function in the `storage` block. Then, you can add an `executions` or `jobs` block that re-runs the function and updates the global variables. This way, you can re-fetch the data whenever you want, or automatically every so often (if using a job), without reloading the plugin.

**Comment by elioengcomp** [comment]
Hi @sarathkrishna2018 ,

I agree with @DarthFennec about the creation of a new custom endpoint using the [executions] (https://www.jfrog.com/confluence/display/RTF/User+Plugins#UserPlugins-Executions) DSL. That will allow you to trigger xyz operations anytime you want via HTTP.

**Comment by sarathkrishna2018** [comment]
Hi @DarthFennec , @elioengcomp 

Indeed it's a good idea using global variables and executions DSL. I'll try that out. Thanks for your replies. I had in my mind to use executions DSL but I missed out on using the idea of Global Variables. Thanks for that.

**Comment by sarathkrishna2018** [comment]
Ya, it worked. Thanks guys. :)
