### ISSUE TITLE
Why webhook will be triggered three times after an event

### ISSUE THREAD

**Issue by windghoul** [jfrog/artifactory-user-plugins#294]
![image](https://user-images.githubusercontent.com/16053291/66568387-ea9b1100-eb9b-11e9-91bc-f0c27f1b2347.png)
![image](https://user-images.githubusercontent.com/16053291/66568516-2df57f80-eb9c-11e9-9635-c49691a8dfb6.png)
![image](https://user-images.githubusercontent.com/16053291/66568650-7745cf00-eb9c-11e9-8d14-f30e8c957e44.png)
Our cluster is a two-node high-availability cluster, and the plug-in for the webhook used is not modified in the original version, only the conf file is modified.
When using the curl tool to make a props modification request, the return is not 200, which is 204.
thank you

**Comment by jfrog-aparicio** [comment]
The webhook is just listening to the [afterPropertyCreate event](https://www.jfrog.com/confluence/display/RTF/User+Plugins#UserPlugins-Storage) of the plugin mechanism. This means that the action you are performing is causing the event to be triggered three times. This could be because you are modifying multiple properties. What does your request look like?

**Comment by windghoul** [comment]
[log.txt](https://github.com/jfrog/artifactory-user-plugins/files/3715262/log.txt)
This is my log, I used the diff tool, except for the timestamp, the rest of the body content is exactly the same. And this request is also the time and number of requests that match the system log.
thank you

**Comment by jfrog-aparicio** [comment]
Unable to reproduce. In any case, we recommend you use the new built-in Artifactory webhook feature.
