### ISSUE TITLE
artifactCleanup.groovy no delete permissions

### ISSUE THREAD

**Issue by YakirShriker** [jfrog/artifactory-user-plugins#307]
Hi, I'm running Artifactory 6.16
configured artifactCleanup.groovy and deletion JSON.
I see an error in logs:
`2020-01-15 14:22:04,331 [http-nio-8081-exec-7] [INFO ] (artifactCleanup     :232) - From that 0 artifacts no delete permission by user (0 bytes)`

**Comment by DarthFennec** [comment]
This is a poorly worded log, to be sure. It means that out of the artifacts that the plugin attempted to delete, the number that couldn't be deleted because of lack of permissions is zero. So essentially this is a success message.

I've changed the message to be a little more readable, and it will no longer appear at all unless there are some artifacts that couldn't be deleted. Thanks!

**Comment by YakirShriker** [comment]
Thank you!
