### ISSUE TITLE
updatePropertySet is not working as expected for propertySetsConfig plugin

### ISSUE THREAD

**Issue by pavanvikas** [jfrog/artifactory-user-plugins#308]
When I try to update property values for an existing properset using **updatePropertySet** the existing fields of this property set disappear and only the updated ones remain.

When he uses updatePropertySet ideally the property values should get updated to the existing property set. But instead of that existing fields of this property set disappear and only the updated ones remains. I have attached the screenshots for your reference.

![After-plugin-triggered](https://user-images.githubusercontent.com/49061570/73775744-7caed100-47ac-11ea-8c0d-c0bb0481929d.jpg)
![Before-plugin](https://user-images.githubusercontent.com/49061570/73775746-7caed100-47ac-11ea-9ab7-8f812c245933.jpg)

**Command used:**
curl -u admin:<password> -X POST -H 'Content-Type: application/json' -d '{
"name" : "sample",
 "properties": [{
 "name": "name1",
 "propertyType": "Any Value",
 "predefinedValues": [{"value": "fdsafdas", "defaultValue": true}],
 }]
 }' 'http://ARTIFACTORY-URL/artifactory/api/plugins/execute/updatePropertySet?params=name=sample'

**Comment by DarthFennec** [comment]
From what I can tell, this is expected behavior. `updatePropertySet` can be used to add or overwrite properties to an existing property set. When you specify an existing property with a new set of predefined values, it replaces the old default values for that property.

If you want to preserve your old predefined values, you need to include them in your new list.
