### ISSUE TITLE
Pommer: black and whitelist feature

### ISSUE THREAD

**Issue by irrandon** [jfrog/artifactory-user-plugins#314]
add a black and whitelist funktion for the pommer plugin.
It is configurable via the pommer.json

**Comment by nehamjfrog** [comment]
Thank you for this function request. We appreciate all user input. However, since this request has been dormant for some time and several plugins have been deprecated in the latest releases, we are closing it for now. If you have any updates or consider this feature is still important, please reopen it or submit a new request with the most current information.
