### ISSUE TITLE
Question: How to run artifactCleanup plugin as scheduled jobs 

### ISSUE THREAD

**Issue by kaushalringle** [jfrog/artifactory-user-plugins#316]
Question about ArtifactCleanup plugin. 

How can i run this plugin on a schedule using artifactCleanup.json. 

The readme file says we can run it using 2 ways REST API or as scheduled Jobs.

I have installed the plugin and i am able run it via REST API as CURL commands. 

I have placed the same parameters in artifactCleanup.json and reload the plan using /artifactory/api/plugins/reload. 

i can see in artifactory logs that the Cron never runs. Am i missing something ? How to enable the scheduled execution for this plugin. 

Here is the policy that i have in artifactCleanup.json

{
    "policies": [
        {
            "cron": "0 30 19 ? * * *",
            "repos": [
                "maven-local"
            ],
            "timeUnit": "month",
            "timeInterval": 6,
            "dryRun": true,
            "paceTimeMS": 100,
            "disablePropertiesSupport": true
        }
    ]
}

**Comment by DarthFennec** [comment]
Your config looks correct, so that shouldn't be the problem. If you're running Artifactory HA, make sure the groovy and json files are both present on all nodes, and you may need to run the reload API on all nodes as well, rather than just on the load balancer. If this doesn't work, you can try restarting Artifactory, if that's an option for you.

**Comment by kaushalringle** [comment]
resolution!

Creating an empty file artifactCleanup.properties under /artifactory/etc/plugins and reloading the plugin worked for me. 

Now i can the crons are running based on what is specified in artifactCleanup.json
