### ISSUE TITLE
add feature to keep last 3 artifacts

### ISSUE THREAD

**Issue by davkohli** [jfrog/artifactory-user-plugins#322]
Can we add feature to delete all artifacts except last 3 (or n artifacts) alongside the artifact deletion for 'n' timeframe? Because if any team does not deployed artifacts for last 'n' timeframe, we should still have last n artifacts. Thanks.

**Comment by IliaGershenzon** [comment]
Joining the request, can't understand why "Not downloaded for X timeframe' is more logic than "Keep last N versions of the artifact"

**Comment by jfrog-aparicio** [comment]
Plugin: artifactCleanup

**Comment by mattpascoe** [comment]
I see this as a required option.  We are building RPM and DEB packages to be deployed in our environment.  I need to have at least one package always available.  Its entirely possible I could go through a cycle of creating 20 packages in a day and then go for months without updating it. 

If we were to build a new system that required this package and this cleanup job had deleted anything older than 3 months for example, I wouldnt have a package available for the new system to utilize because it would have been removed.

There must be both an age calculation as well as a threshold to keep N number of newest artifacts.

**Comment by harendrar8095** [comment]
Thanks for bringing this up!

As you can see in [our documentation](https://jfrog.com/help/r/jfrog-platform-administration-documentation/package-types-coverage), we are working on a newer, recommended way to extend the JFrog Platform (including Artifactory) in a cloud-native way, called JFrog Workers. Unfortunately, this means that our focus and resources are directed toward that initiative, and we are not able to take any new feature requests at this time.

We’re closing this for now, but feel free to reopen it if you have any further queries!
