### ISSUE TITLE
New parameter - keep a number of artifacts per folder

### ISSUE THREAD

**Issue by VAlexN** [jfrog/artifactory-user-plugins#323]
Hi,

I don't think I'm the first one asking for this feature but adding a new parameter like "keepLastNoArtifacts" based on the last downloaded artifacts or creation date would be a very nice addition. From what I saw, AQL was introduced recently in this script which maybe should do the trick using `sort` and `offset` but from my knowledge in a complex folder structure, AQL will not work as expected.

Thank you,
Alex

**Comment by nehamjfrog** [comment]
Thank you for this function request. We appreciate all user input. However, since this request has been dormant for some time and several plugins have been deprecated in the latest releases, we are closing it for now. If you have any updates or consider this feature is still important, please reopen it or submit a new request with the most current information.
