### ISSUE TITLE
Does the securityReplication plugin works for Artifactory 7?

### ISSUE THREAD

**Issue by GolanTrevize10** [jfrog/artifactory-user-plugins#325]
Hi all, does the securityReplication  plugin works for Artifactory 7? I saw the latest commit by @DarthFennec is a fix for Artifactory 7 but when I try to deploy  it says that the ArtifactoryHome class does not exist.

**Comment by DarthFennec** [comment]
My mistake. That commit was a blanket change to fix an issue that affected a number of plugins. When I made it, I didn't check to make sure I wasn't changing plugins that were already unsupported in Artifactory 6.

As stated in the [README](https://github.com/jfrog/artifactory-user-plugins/blob/master/security/securityReplication/README.md), securityReplication has been deprecated in favor of Access Federation since Artifactory 6, so it's not supported in 7 either. Sorry for the confusion.

**Comment by GolanTrevize10** [comment]
@DarthFennec I know it is deprecated but would it work in ARtifactory 7? Access Federation is not available in Artifactory Enterprise

**Comment by DarthFennec** [comment]
The plugin depends on a few things that have changed since Artifactory 6, such as the ArtifactoryHome class (as you've seen). Because of this, no, it doesn't work in Artifactory 7. Sorry.
