### ISSUE TITLE
remoteBackup: plugin shouldn't overwrite 

### ISSUE THREAD

**Issue by beasleyr-vmw** [jfrog/artifactory-user-plugins#352]
I discovered the remoteBackup plugin via https://jfrog.com/knowledge-base/how-remote-repository-metadata-works/ . I want to use this plugin to guarantee build reproducibility.

Using the repository layout described in that KB article, suppose I have something like this:

* maven (virtual)
    * maven-local
    * central-remote
        * central-remote-cache
    * jcenter-remote
        * jcenter-remote-cache

Next, suppose I've deployed the remoteBackup plugin with a config file indicating that writes to central-remote-cache and jcenter-remote-cache should be backed up to maven-local.

And finally, suppose that there's a Maven artifact with identical coordinates/path but which central and jcenter have distinct copies of. (Real example: net.minidev:asm:1.0.2.)

If user actions trigger alternating downloads against central-remote and jcenter-remote, each download will cause the plugin to overwrite the copy kept in maven-local. This is not expected behavior and somewhat contradicts the knowledge base article:

> There are some drawbacks to this approach. Usually packages are deleted for a good reason, and there may be some risk in continuing to use a deprecated package. Package overwrites will also never appear, as the old local files will be served first.

(The KB assumes nobody will ever directly fetch from the associated remote repositories.)

While still racy, this may be mitigated w/ the following patch:

```diff
diff --git a/storage/remoteBackup/remoteBackup.groovy b/storage/remoteBackup/remoteBackup.groovy
index cfa8003..78d3b8e 100644
--- a/storage/remoteBackup/remoteBackup.groovy
+++ b/storage/remoteBackup/remoteBackup.groovy
@@ -57,7 +57,9 @@ storage {
         def dest = cfg[item.repoKey]
         try {
           def destpath = RepoPathFactory.create(dest, item.relPath)
-          repositories.copy(item.repoPath, destpath)
+          if (!repositories.exists(destpath)) {
+            repositories.copy(item.repoPath, destpath)
+          }
         } catch (Exception ex) {
           log.warn("Unable to backup $item.repoPath to $dest: $ex.message")
         }
```

**Comment by peters95** [comment]
Hi @beasleyr-vmw I suspect you're trying to use this plugin for a scenario that was not its intended design.

"I want to use this plugin to guarantee build reproducibility."

Build reproducibility is a tricky subject and could easily fail for a whole host of reasons. I'm not exactly sure why the two are related as this plugin is only for remoteBackup.

I don't think we want to add the desired code above because while it may solve your scenario it breaks the mantra of "backups" which would override the artifact to ensure the backup is fresh and up to date in the case of mutable artifacts like docker images.

Also, most user plugins in this repo are only meant as reference examples in most cases so if you need to add the specific code above for your use case you can always make the modifications locally before applying the plugin to your Artifactory.

**Comment by beasleyr-vmw** [comment]
Hi @peters95,

All points are well taken. I'll go ahead and resolve this.

Thanks for the prompt response!
