### ISSUE TITLE
compatibility issues with inactiveServerCleaner user plugin from Artifactory 7.x

### ISSUE THREAD

**Issue by pavanvikas** [jfrog/artifactory-user-plugins#369]
User plugin **[inactiveServerCleaner](https://github.com/jfrog/artifactory-user-plugins/tree/master/ha/inactiveServerCleaner)**, is not working with Artifactory latest 7.x versions.

Please find below the steps to replicate: 

**Environment used**:
Artifactory v7.12.8

 1. Install Artifactory HA cluster with primary and member nodes.
 2. Copy **inactiveServerCleaner.groovy** script to $JFROG-HOME/artifactory/var/etc/artifactory/plugins directory
 3. After the successful copy, please execute [ReloadPlugins](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-ReloadPlugins) REST API to reload the user plugin.

If the one of Artifactory member node is in a failure state, I still see nodes that are unavailable. Please find the below screenshot for reference.

**Comment by pavanvikas** [comment]
![HA-nodes-status](https://user-images.githubusercontent.com/49061570/108605516-73ee6480-73da-11eb-9317-22dce4516319.jpg)

**Comment by harendrar8095** [comment]
Thanks for reaching out!

This plugin is deprecated due to non-compliance and is no longer supported. As part of our ongoing plugin [deprecation plan](https://jfrog.com/help/r/jfrog-release-information/artifactory-deprecations), we encourage you to adopt the new approach for extending Artifactory functionality using JFrog Workers.

We’re closing this for now, but feel free to reopen it if you have further questions!
