### ISSUE TITLE
expireFilesMetadata deprecation

### ISSUE THREAD

**Issue by alexmJH** [jfrog/artifactory-user-plugins#448]
@shrajfr12 I saw that you've deprecated the expireFilesMetadata plugin.
Is there any specific reason?
We are using it to enable msys2 repositories among a few others and would like to continue using it in the future.

**Comment by beavis6511** [comment]
Hi,
I'm also using this plugin for generic repositories who can't "detect" a change on a remote upstream website.
I'm worried to see it deprecated.
The answer of jfrog support is:

Please be informed that as mentioned in our[ GitHub page](https://github.com/jfrog/artifactory-user-plugins/tree/master/deprecated-plugins) the directory “deprecated-plugins” contains all the plugins that have been deprecated as of Artifactory 7.43. The plugin contains dependencies on internal RT code. Due to some security concerns, the dependent code is no longer packaged in the latest versions of Artifactory. Which will break the plugin functionality post Artifactory upgrade from 7.43 and above.

**Comment by alexmJH** [comment]
Hi @beavis6511,
thanks for the info.
I've just opened a ticket with JFrog as well and asked for some further clarification. I've asked them to directly reply to this issue, if they get back to me directly I will update the issue rewardingly.

**Comment by friesoft** [comment]
Any news on this? We are trying to mirror cpan with Artifactory but without this plugin it won't work

**Comment by alexmJH** [comment]
JFrog has sent me a very [rudimentary implementation](https://github.com/jfrog/artifactory-user-plugins/files/13599093/expireFileinRepos.groovy.txt) of a successor. That however is so incomplete that it's not really usable in production.
As we haven't gotten around to updating our Artifactory cluster yet we are still running expireFilesMetadata. 
Once we do update I will implement a production-ready plugin (unless someone does so before I get to it :) )

**Comment by shashank-jfrog** [comment]
Thank you for your question. However, since this question has been inactive for some time and many plugins have been deprecated in the latest versions, we are closing it for now. If you have updates or if this question is still relevant, please feel free to reopen it or submit a new request with the latest details.

**Comment by NicklasWallgren** [comment]
Is there any successor to the expireFilesMetadata-plugin?
