### ISSUE TITLE
 GitKraken integration with Artifactory

### ISSUE THREAD

**Issue by srigokulcss** [jfrog/artifactory-user-plugins#451]
Hi,

Need an IDE/Plugin to integrate GitKraken with Artifactory, currently there is no method to integrate GitKraken with Artifactory.

Thanks,
Srigokul S

**Comment by shashank-jfrog** [comment]
Hi,
Thank you for your feature request. We appreciate all user input. However, since this request has been inactive for some time and many plugins have been deprecated in the latest versions, we are closing it for now. If you have updates or if this feature is still relevant, please feel free to reopen it or submit a new request with the latest details.
